name: Frontend CI
run-name: Frontend CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 19.7.0
      uses: actions/setup-node@v3
      with:
        node-version: "19.7.0"
        cache: 'npm'

    - name: Install dependencies
      run: npm install 

    - name: Check linting and formatting
      run: npm run lint 
      
    - name: Run tests
      run: npm run test 
